### ISSUE TITLE
3D Printing Recommendations

### ISSUE THREAD

**Issue by M-A-Robson** [dougsm/egad#1]
Thank you for making this work so accessible. For the experiments in the paper can you share what method of 3D printing was used for the evaluation objects?
If FDM - do you have any recommendations on material, layer heights, support, infill or raft settings?

**Comment by dougsm** [comment]
Hi @M-A-Robson, great question, I should add some information about this to the readme.

You milage may differ depending on printer, but in the Up Studio software with a Cetus3D printer, the following settings worked for most of the objects no problem:
* Filament: PLA
* Layer Height: 0.2mm
* Nozzle: 0.6mm
* Infill: 20%
* Quality: Normal
* Raft: Yes
* Support: Yes
* Support Threshold: 40 Deg

In my experience, for some of the simpler objects (i.e. basic shapes) you can speed everything up by upping the layer height and having less infill without any bad effects. 

Apologies that I don't have a better photo, but if it helps, this is what they looked like on the bed. You can play with most of the objects' orientations such that minimal support material is required which makes cleaning them up a lot easier.

![image](https://user-images.githubusercontent.com/26375098/84959048-f1721e80-b141-11ea-854d-1827cc3c7abb.png)

**Comment by M-A-Robson** [comment]
Thanks for the quick reply!
