### ISSUE TITLE
Unable to download the dataset

### ISSUE THREAD

**Issue by jelenatabak** [dougsm/egad#10]
Hello,

I'm unable to download the dataset using the link provided on the project website (The connection has timed out - An error occurred during a connection to data.researchdatafinder.qut.edu.au.). Could you please provide an alternative download link?

Thank you in advance!

**Comment by dougsm** [comment]
Hei Jelena, I've uploaded the files temporarily here: https://s.dougsm.com/egad/ 
Sorry for the inconvenience.

**Comment by jelenatabak** [comment]
Thank you!
