### ISSUE TITLE
Stable resting poses of the meshes

### ISSUE THREAD

**Issue by jsll** [dougsm/egad#4]
Hi,

First of all, this dataset is great. I have used it for some of my work and it really poses some difficult to grasp objects.

I now want to use the objects inside a simulation environment (in my case PyBullet). However, for this I'd like to know all stable resting poses of the objects. For instance, is the y-axis always pointing in one stable resting pose? I have visualized a few objects using Trimesh (an example is shown below) and those have at least had the y-axis in a stable resting pose.  

![image](https://user-images.githubusercontent.com/24250493/103271084-ec7c0a80-49c1-11eb-8cdf-637f305025b0.png)

**Comment by dougsm** [comment]
Hey @jsll, glad you're finding the dataset useful.  The orienatation of the mesh files is arbitraty, just aligned to the output of the CPPN.  If you need to know the stable poses, easiest way would be to compute them with trimesh, which will give you a list of possible stable poses and their probabilities: https://trimsh.org/trimesh.poses.html#trimesh.poses.compute_stable_poses

**Comment by jsll** [comment]
Thanks for your swift answer. I can confirm that using https://trimsh.org/trimesh.poses.html#trimesh.poses.compute_stable_poses seems to give quite reasonable results.

I will close this now.
