### ISSUE TITLE
Question on collision checking

### ISSUE THREAD

**Issue by aprath1** [dougsm/egad#6]
Thank you so much for open sourcing this great work, egad!

I am working on an object grasping task, I could see that your approach is compatible with dex-net and is also capable of creating dex-net datases. My question is are you applying collision check while creating dex-net dataset? If you are could you please let me know how you installed openrave (jeffmahler/openrave) for collision check? 

I am facing multiple issues with the openrave conflicting with Moby, just can't figure out which branch of Moby is compatible with the openrave for dexnet ( I tried multiple branches of Moby like master. new-Ravelin, IPOPT, NewCCD, openrave etc...). Also would be nice to know the compatible Ravelin branch too?

Thank you in advance

**Comment by dougsm** [comment]
No, I don't believe it uses openrave for collision checking.  Sorry I can't be more help. 

You can see the whole installation script that I used here: https://github.com/dougsm/egad/blob/master/singularity/singularity.def

**Comment by aprath1** [comment]
Thank you for your response. I could see in the dex-net deployment package in the singularity.def; there is a file tools/generate_gqcnn_dataset.py which uses  'GraspCollisionChecker' imported from src/dexnet/grasping/collision_checker.py. Inside this collision_checker.py file there is an import 'import openravepy as rave' and the collision checks in dex-net gqcnn data generation is depending on this import. 

Based on this I was asking this question about openrave. So in case you did not use openrave, could you kindly let me know if you have considered any alternatives or was your approach to generate dataset for gqcnn different ?

This information could also help in general to use the 'egad.hdf5' dataset (dex-net compatible dataset mentioned in your project website) for training a gqcnn network.

Thanks again!

**Comment by aprath1** [comment]
It seems like there was a bug in the openrave connected with dexnet; by removing import of Eulerintgrator in the mobyrave plugin the installation error in openrave could be solved. 
But for the database generation and grasp quality computation openrave is not required.
