### ISSUE TITLE
Question on weight initialization

### ISSUE THREAD

**Issue by aprath1** [dougsm/egad#7]
Hi @dougsm ,

Could you please let me know how are the weights initialized for the CPPN? Is it random or zero initialisation; also would be interesting to know if all the inputs are fully connected to the output for the initial meshes.
As far as I understand at first a workspace of x,y,z ranging between -1 and 1 is created and then using this as input initial meshes are generated, is this correct? 

Thanks in advance

**Comment by dougsm** [comment]
Hi,
- I believe the weights are randomly initialised according to the configuration options (look for `*_init_*` in the config files, e.g. https://github.com/dougsm/egad/blob/master/egad/config_cppn_voxgrids_default#L23)
- The connections from input to output are initially connected with probability 0.5: https://github.com/dougsm/egad/blob/master/egad/config_cppn_voxgrids_default#L44
- Yes, your understanding is correct.  The input space is always -1 to 1 in x, y and z.

You can read more about the configuration options here: https://neat-python.readthedocs.io/en/latest/config_file.html#initial-connection-config-label

**Comment by aprath1** [comment]
Hi, 

I was actually able to figure it out by debugging and some research, and forgot to post it here. 

**I really appreciate your time to post the answer and the links, Thank you!**

**Comment by dougsm** [comment]
Sorry I took so long to reply.
